import type { McpCatalogEntry } from "./types/mcp-server.js";

/**
 * Curated catalog of MCP servers that are useful for a marketing-oriented
 * company. Entries marked `experimental` do not have an official upstream
 * MCP server yet — the `command` / `url` values point to the most-likely
 * community implementation or leave placeholders that the operator must
 * replace. Secrets are never embedded here; only the expected env-key
 * names are declared.
 */
export const MARKETING_MCP_CATALOG: McpCatalogEntry[] = [
  // ============================================================ analytics
  {
    key: "google-analytics-4",
    name: "Google Analytics 4",
    description: "Query GA4 property reports, realtime data and audiences.",
    category: "analytics",
    status: "experimental",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@surendrajat/mcp-ga4"],
    envKeys: [
      { key: "GA_PROPERTY_ID", label: "GA4 Property ID", required: true },
      { key: "GOOGLE_APPLICATION_CREDENTIALS", label: "Service Account JSON path", required: true, docsUrl: "https://cloud.google.com/docs/authentication/application-default-credentials" },
    ],
    docsUrl: "https://developers.google.com/analytics/devguides/reporting/data/v1",
    isStarterPack: true,
  },
  {
    key: "google-search-console",
    name: "Google Search Console",
    description: "SEO-posities, indexering, clicks en impressies per query.",
    category: "analytics",
    status: "experimental",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-gsc"],
    envKeys: [
      { key: "GOOGLE_APPLICATION_CREDENTIALS", label: "Service Account JSON path", required: true },
      { key: "GSC_SITE_URL", label: "Site URL (https://example.com/)", required: true },
    ],
    docsUrl: "https://developers.google.com/webmaster-tools",
    isStarterPack: false,
  },
  {
    key: "plausible",
    name: "Plausible Analytics",
    description: "Privacy-vriendelijke web-analytics (stats, goals, funnels).",
    category: "analytics",
    status: "experimental",
    transport: "http",
    url: "https://plausible.io/api/v2",
    headerKeys: [{ key: "Authorization", label: "Bearer <API key>", required: true }],
    envKeys: [{ key: "PLAUSIBLE_SITE_ID", label: "Site ID", required: true }],
    docsUrl: "https://plausible.io/docs/stats-api",
    isStarterPack: false,
  },
  {
    key: "hotjar-clarity",
    name: "Microsoft Clarity / Hotjar",
    description: "Heatmaps en sessieopnames voor UX-inzichten.",
    category: "analytics",
    status: "experimental",
    transport: "http",
    url: "https://www.clarity.ms/export-data/api/v1",
    headerKeys: [{ key: "Authorization", label: "Bearer <token>", required: true }],
    envKeys: [{ key: "CLARITY_PROJECT_ID", label: "Clarity Project ID", required: true }],
    docsUrl: "https://learn.microsoft.com/en-us/clarity/setup-and-installation/clarity-data-export-api",
    isStarterPack: false,
  },

  // ============================================================ advertising
  {
    key: "google-ads",
    name: "Google Ads",
    description: "Campagnes, bied-strategieën en performance-rapportage.",
    category: "advertising",
    status: "experimental",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-google-ads"],
    envKeys: [
      { key: "GOOGLE_ADS_DEVELOPER_TOKEN", label: "Developer Token", required: true },
      { key: "GOOGLE_ADS_CLIENT_ID", label: "OAuth Client ID", required: true },
      { key: "GOOGLE_ADS_CLIENT_SECRET", label: "OAuth Client Secret", required: true },
      { key: "GOOGLE_ADS_REFRESH_TOKEN", label: "Refresh Token", required: true },
      { key: "GOOGLE_ADS_CUSTOMER_ID", label: "Customer ID (123-456-7890)", required: true },
    ],
    docsUrl: "https://developers.google.com/google-ads/api/docs/start",
    isStarterPack: false,
  },
  {
    key: "meta-ads",
    name: "Meta Ads (Facebook/Instagram)",
    description: "Beheer van advertentiecampagnes, ad-sets en creatives.",
    category: "advertising",
    status: "experimental",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-meta-ads"],
    envKeys: [
      { key: "META_ACCESS_TOKEN", label: "Long-lived access token", required: true },
      { key: "META_AD_ACCOUNT_ID", label: "Ad Account ID (act_xxx)", required: true },
    ],
    docsUrl: "https://developers.facebook.com/docs/marketing-apis",
    isStarterPack: false,
  },
  {
    key: "linkedin-ads",
    name: "LinkedIn Ads",
    description: "LinkedIn Marketing-API voor campagnes en lead-gen.",
    category: "advertising",
    status: "experimental",
    transport: "http",
    url: "https://api.linkedin.com/rest",
    headerKeys: [
      { key: "Authorization", label: "Bearer <access token>", required: true },
      { key: "LinkedIn-Version", label: "API versie (bv. 202404)", required: true },
    ],
    envKeys: [{ key: "LINKEDIN_AD_ACCOUNT_ID", label: "Ad Account URN", required: true }],
    docsUrl: "https://learn.microsoft.com/en-us/linkedin/marketing/",
    isStarterPack: false,
  },

  // ============================================================ social
  {
    key: "linkedin",
    name: "LinkedIn",
    description: "Posts, company pages, profielen en lead-gen forms.",
    category: "social",
    status: "experimental",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-linkedin"],
    envKeys: [{ key: "LINKEDIN_ACCESS_TOKEN", label: "OAuth access token", required: true }],
    docsUrl: "https://learn.microsoft.com/en-us/linkedin/",
    isStarterPack: true,
  },
  {
    key: "meta-graph",
    name: "Meta Graph (Facebook / Instagram)",
    description: "Publiceer posts, lees insights en comments.",
    category: "social",
    status: "experimental",
    transport: "http",
    url: "https://graph.facebook.com/v19.0",
    headerKeys: [{ key: "Authorization", label: "Bearer <token>", required: true }],
    envKeys: [{ key: "META_PAGE_ID", label: "Page ID", required: true }],
    docsUrl: "https://developers.facebook.com/docs/graph-api",
    isStarterPack: false,
  },
  {
    key: "tiktok-business",
    name: "TikTok Business",
    description: "Content-publicatie en performance-rapportage voor TikTok.",
    category: "social",
    status: "experimental",
    transport: "http",
    url: "https://business-api.tiktok.com/open_api/v1.3",
    headerKeys: [{ key: "Access-Token", label: "Access token", required: true }],
    envKeys: [{ key: "TIKTOK_ADVERTISER_ID", label: "Advertiser ID", required: true }],
    docsUrl: "https://business-api.tiktok.com/portal/docs",
    isStarterPack: false,
  },
  {
    key: "youtube-data",
    name: "YouTube Data API",
    description: "Uploads, kanaalstatistieken, comments en playlists.",
    category: "social",
    status: "experimental",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-youtube"],
    envKeys: [
      { key: "YOUTUBE_API_KEY", label: "API key of OAuth token", required: true },
      { key: "YOUTUBE_CHANNEL_ID", label: "Kanaal ID", required: false },
    ],
    docsUrl: "https://developers.google.com/youtube/v3",
    isStarterPack: false,
  },
  {
    key: "buffer",
    name: "Buffer",
    description: "Centrale scheduling van posts over social-kanalen.",
    category: "social",
    status: "experimental",
    transport: "http",
    url: "https://api.bufferapp.com/1",
    headerKeys: [{ key: "Authorization", label: "Bearer <access token>", required: true }],
    envKeys: [],
    docsUrl: "https://buffer.com/developers/api",
    isStarterPack: false,
  },

  // ============================================================ content
  {
    key: "notion",
    name: "Notion",
    description: "Contentkalender, briefings en redactionele workflow.",
    category: "content",
    status: "stable",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@notionhq/notion-mcp-server"],
    envKeys: [{ key: "NOTION_API_KEY", label: "Internal Integration Token", required: true }],
    docsUrl: "https://developers.notion.com/",
    isStarterPack: false,
  },
  {
    key: "google-docs",
    name: "Google Docs / Drive",
    description: "Documenten lezen en genereren voor content-productie.",
    category: "content",
    status: "experimental",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-gdrive"],
    envKeys: [{ key: "GOOGLE_APPLICATION_CREDENTIALS", label: "Service Account JSON", required: true }],
    docsUrl: "https://developers.google.com/docs/api",
    isStarterPack: false,
  },
  {
    key: "grammarly",
    name: "Grammarly / LanguageTool",
    description: "Tekstcontrole, stijl en tone-of-voice.",
    category: "content",
    status: "experimental",
    transport: "http",
    url: "https://api.languagetool.org/v2",
    headerKeys: [],
    envKeys: [{ key: "LT_USERNAME", label: "LanguageTool username (optioneel)", required: false }],
    docsUrl: "https://languagetool.org/http-api/",
    isStarterPack: false,
  },

  // ============================================================ design
  {
    key: "canva",
    name: "Canva",
    description: "Social posts, banners en presentaties on-brand genereren.",
    category: "design",
    status: "stable",
    transport: "http",
    url: "https://mcp.canva.com/",
    headerKeys: [{ key: "Authorization", label: "Bearer <OAuth token>", required: true }],
    envKeys: [],
    docsUrl: "https://www.canva.dev/docs/connect/",
    isStarterPack: false,
  },
  {
    key: "figma",
    name: "Figma",
    description: "Design-review, asset-export en brand-consistency checks.",
    category: "design",
    status: "stable",
    transport: "stdio",
    command: "npx",
    args: ["-y", "figma-developer-mcp", "--stdio"],
    envKeys: [{ key: "FIGMA_API_KEY", label: "Personal Access Token", required: true }],
    docsUrl: "https://www.figma.com/developers/api",
    isStarterPack: false,
  },
  {
    key: "adobe-express",
    name: "Adobe Express / Photoshop",
    description: "Professionele asset-bewerking via Adobe APIs.",
    category: "design",
    status: "experimental",
    transport: "http",
    url: "https://image.adobe.io/pie/psdService",
    headerKeys: [
      { key: "Authorization", label: "Bearer <access token>", required: true },
      { key: "x-api-key", label: "Adobe API key", required: true },
    ],
    envKeys: [],
    docsUrl: "https://developer.adobe.com/firefly-services/docs/photoshop/",
    isStarterPack: false,
  },

  // ============================================================ email
  {
    key: "mailchimp",
    name: "Mailchimp",
    description: "Nieuwsbriefbeheer, audience-segmenten en campagnes.",
    category: "email",
    status: "experimental",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-mailchimp"],
    envKeys: [
      { key: "MAILCHIMP_API_KEY", label: "API key (eindigt op -usX)", required: true },
      { key: "MAILCHIMP_SERVER_PREFIX", label: "Server prefix (bv. us21)", required: true },
    ],
    docsUrl: "https://mailchimp.com/developer/marketing/api/",
    isStarterPack: true,
  },
  {
    key: "resend",
    name: "Resend",
    description: "Transactionele en marketing e-mail via API.",
    category: "email",
    status: "stable",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@resend/mcp-send-email"],
    envKeys: [
      { key: "RESEND_API_KEY", label: "Resend API key", required: true },
      { key: "SENDER_EMAIL_ADDRESS", label: "Afzender e-mail", required: true },
    ],
    docsUrl: "https://resend.com/docs/send-with-mcp",
    isStarterPack: false,
  },
  {
    key: "brevo",
    name: "Brevo (Sendinblue)",
    description: "Email/SMS campagnes en marketing automation.",
    category: "email",
    status: "experimental",
    transport: "http",
    url: "https://api.brevo.com/v3",
    headerKeys: [{ key: "api-key", label: "Brevo API key", required: true }],
    envKeys: [],
    docsUrl: "https://developers.brevo.com/",
    isStarterPack: false,
  },
  {
    key: "klaviyo",
    name: "Klaviyo",
    description: "E-commerce email en SMS flows.",
    category: "email",
    status: "experimental",
    transport: "http",
    url: "https://a.klaviyo.com/api",
    headerKeys: [
      { key: "Authorization", label: "Klaviyo-API-Key <key>", required: true },
      { key: "revision", label: "API-revisie (bv. 2024-10-15)", required: true },
    ],
    envKeys: [],
    docsUrl: "https://developers.klaviyo.com/",
    isStarterPack: false,
  },

  // ============================================================ seo
  {
    key: "ahrefs",
    name: "Ahrefs",
    description: "Keyword research, backlinks en concurrentie-analyse.",
    category: "seo",
    status: "experimental",
    transport: "http",
    url: "https://api.ahrefs.com/v3",
    headerKeys: [{ key: "Authorization", label: "Bearer <API token>", required: true }],
    envKeys: [],
    docsUrl: "https://ahrefs.com/api/documentation",
    isStarterPack: true,
  },
  {
    key: "semrush",
    name: "SEMrush",
    description: "Keyword-data, domein-audits en rank-tracking.",
    category: "seo",
    status: "experimental",
    transport: "http",
    url: "https://api.semrush.com",
    headerKeys: [],
    envKeys: [{ key: "SEMRUSH_API_KEY", label: "API key", required: true }],
    docsUrl: "https://www.semrush.com/api-documentation/",
    isStarterPack: false,
  },
  {
    key: "screaming-frog",
    name: "Screaming Frog",
    description: "Technische SEO-audits (crawl via lokale CLI).",
    category: "seo",
    status: "experimental",
    transport: "stdio",
    command: "screamingfrogseospider",
    args: ["--headless", "--crawl"],
    envKeys: [{ key: "SF_LICENSE_KEY", label: "Licentie-key", required: false }],
    docsUrl: "https://www.screamingfrog.co.uk/seo-spider/user-guide/",
    isStarterPack: false,
  },
  {
    key: "similarweb",
    name: "SimilarWeb",
    description: "Concurrentieanalyse, marktaandeel en traffic-bronnen.",
    category: "seo",
    status: "experimental",
    transport: "http",
    url: "https://api.similarweb.com/v1",
    headerKeys: [],
    envKeys: [{ key: "SIMILARWEB_API_KEY", label: "API key", required: true }],
    docsUrl: "https://developers.similarweb.com/",
    isStarterPack: false,
  },

  // ============================================================ crm
  {
    key: "hubspot",
    name: "HubSpot",
    description: "CRM + marketing-automation in één: contacts, deals, campaigns.",
    category: "crm",
    status: "experimental",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@hubspot/mcp-server"],
    envKeys: [{ key: "PRIVATE_APP_ACCESS_TOKEN", label: "HubSpot private app token", required: true }],
    docsUrl: "https://developers.hubspot.com/docs/api/overview",
    isStarterPack: true,
  },
  {
    key: "salesforce",
    name: "Salesforce",
    description: "Leads, accounts, opportunities uit Salesforce CRM.",
    category: "crm",
    status: "experimental",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-salesforce"],
    envKeys: [
      { key: "SALESFORCE_INSTANCE_URL", label: "Instance URL", required: true },
      { key: "SALESFORCE_ACCESS_TOKEN", label: "OAuth access token", required: true },
    ],
    docsUrl: "https://developer.salesforce.com/docs",
    isStarterPack: false,
  },
  {
    key: "pipedrive",
    name: "Pipedrive",
    description: "Sales-pipeline, deals en activities.",
    category: "crm",
    status: "experimental",
    transport: "http",
    url: "https://api.pipedrive.com/v1",
    headerKeys: [],
    envKeys: [{ key: "PIPEDRIVE_API_TOKEN", label: "API token", required: true }],
    docsUrl: "https://developers.pipedrive.com/",
    isStarterPack: false,
  },
  {
    key: "apollo",
    name: "Apollo.io",
    description: "Prospecting: contact-databank en outreach-sequenties.",
    category: "crm",
    status: "experimental",
    transport: "http",
    url: "https://api.apollo.io/v1",
    headerKeys: [{ key: "X-Api-Key", label: "Apollo API key", required: true }],
    envKeys: [],
    docsUrl: "https://docs.apollo.io/",
    isStarterPack: false,
  },

  // ============================================================ ops
  {
    key: "calendly",
    name: "Calendly",
    description: "Afspraken automatisch inplannen en events uitlezen.",
    category: "ops",
    status: "experimental",
    transport: "http",
    url: "https://api.calendly.com",
    headerKeys: [{ key: "Authorization", label: "Bearer <personal token>", required: true }],
    envKeys: [],
    docsUrl: "https://developer.calendly.com/",
    isStarterPack: false,
  },
  {
    key: "apify",
    name: "Apify Actors",
    description: "Web scraping en data-extractie via duizenden kant-en-klare Actors (LinkedIn, Google Maps, Instagram, etc.).",
    category: "ops",
    status: "stable",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@apify/actors-mcp-server"],
    envKeys: [
      { key: "APIFY_TOKEN", label: "Apify API token", required: true, docsUrl: "https://console.apify.com/account/integrations" },
    ],
    docsUrl: "https://docs.apify.com/platform/integrations/mcp",
    isStarterPack: false,
  },
  {
    key: "airtable",
    name: "Airtable",
    description: "Flexibele databases voor campagne- en klant-trackers.",
    category: "ops",
    status: "stable",
    transport: "stdio",
    command: "npx",
    args: ["-y", "airtable-mcp-server"],
    envKeys: [{ key: "AIRTABLE_API_KEY", label: "Personal Access Token", required: true }],
    docsUrl: "https://airtable.com/developers/web/api/introduction",
    isStarterPack: false,
  },
];

export function getCatalogEntry(key: string): McpCatalogEntry | undefined {
  return MARKETING_MCP_CATALOG.find((entry) => entry.key === key);
}

export function getStarterPackEntries(): McpCatalogEntry[] {
  return MARKETING_MCP_CATALOG.filter((entry) => entry.isStarterPack);
}
